In [8]:

import os
import pandas
import numpy
import pickle
import sklearn.ensemble  as ek
from sklearn import cross_validation, tree, linear_model
from sklearn.feature_selection import SelectFromModel
from sklearn.naive_bayes import GaussianNB
from sklearn import preprocessing
from sklearn import svm
from sklearn.linear_model import LinearRegression

C:\Users\Siddharth\Anaconda3\envs\intern_project\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [9]:
dataset = pandas.read_csv('/Users/Siddharth/Anaconda3/envs/intern_project/my_project/data.csv',sep='|', low_memory=False)

In [6]:
dataset.describe()

,Machine,SizeOfOptionalHeader,Characteristics,MajorLinkerVersion,MinorLinkerVersion,SizeOfCode,SizeOfInitializedData,SizeOfUninitializedData,AddressOfEntryPoint,BaseOfCode,...,ResourcesNb,ResourcesMeanEntropy,ResourcesMinEntropy,ResourcesMaxEntropy,ResourcesMeanSize,ResourcesMinSize,ResourcesMaxSize,LoadConfigurationSize,VersionInformationSize,legitimate
count,138047.000000,138047.000000,138047.000000,138047.000000,138047.000000,1.380470e+05,1.380470e+05,1.380470e+05,1.380470e+05,1.380470e+05,...,138047.000000,138047.000000,138047.000000,138047.000000,1.380470e+05,1.380470e+05,1.380470e+05,1.380470e+05,138047.000000,138047.000000
mean,4259.069274,225.845632,4444.145994,8.619774,3.819286,2.425956e+05,4.504867e+05,1.009525e+05,1.719561e+05,5.779845e+04,...,22.050700,4.000127,2.434541,5.521610,5.545093e+04,1.818082e+04,2.465903e+05,4.656750e+05,12.363115,0.299340
std,10880.347245,5.121399,8186.782524,4.088757,11.862675,5.754485e+06,2.101599e+07,1.635288e+07,3.430553e+06,5.527658e+06,...,136.494244,1.112981,0.815577,1.597403,7.799163e+06,6.502369e+06,2.124860e+07,2.608987e+07,6.798878,0.457971
min,332.000000,224.000000,2.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000
25%,332.000000,224.000000,258.000000,8.000000,0.000000,3.020800e+04,2.457600e+04,0.000000e+00,1.272100e+04,4.096000e+03,...,5.000000,3.458505,2.178748,4.828706,9.560000e+02,4.800000e+01,2.216000e+03,0.000000e+00,13.000000,0.000000
50%,332.000000,224.000000,258.000000,9.000000,0.000000,1.136640e+05,2.631680e+05,0.000000e+00,5.288300e+04,4.096000e+03,...,6.000000,3.729824,2.458492,5.317552,2.708154e+03,4.800000e+01,9.640000e+03,7.200000e+01,15.000000,0.000000
75%,332.000000,224.000000,8226.000000,10.000000,0.000000,1.203200e+05,3.850240e+05,0.000000e+00,6.157800e+04,4.096000e+03,...,13.000000,4.233051,2.696833,6.502239,6.558429e+03,1.320000e+02,2.378000e+04,7.200000e+01,16.000000,1.000000
max,34404.000000,352.000000,49551.000000,255.000000,255.000000,1.818587e+09,4.294966e+09,4.294941e+09,1.074484e+09,2.028711e+09,...,7694.000000,7.999723,7.999723,8.000000,2.415919e+09,2.415919e+09,4.294903e+09,4.294967e+09,26.000000,1.000000

In [10]:
dataset.groupby(dataset['legitimate']).size()

legitimate
0    96724
1    41323
dtype: int64

In [11]:
X = dataset.drop(['Name','md5','legitimate'],axis=1).values
y = dataset['legitimate'].values

In [18]:

extratrees  = ek.ExtraTreesClassifier().fit(X,y)
mod = SelectFromModel(extratrees, prefit=True)
X_new = mod.transform(X)
newfeatures = X_new.shape[1]

In [19]:
newfeatures

13

In [20]:
X_train, X_test, y_train, y_test = cross_validation.train_test_split(X_new, y ,test_size=0.2)

In [21]:

features  = []
itereate = numpy.argsort(extratrees.feature_importances_)[::-1][:newfeatures]

In [22]:
for i in range(newfeatures):
    print("%d. feature %s (%f)" % (i + 1, dataset.columns[2+iterate[i]], extratrees.feature_importances_[iterate[i]]))
    features.append(dataset.columns[2+i])

1. feature DllCharacteristics (0.178326)
2. feature Characteristics (0.142994)
3. feature Machine (0.129524)
4. feature Subsystem (0.068007)
5. feature SectionsMaxEntropy (0.051237)
6. feature MajorSubsystemVersion (0.042467)
7. feature VersionInformationSize (0.042435)
8. feature ImageBase (0.032851)
9. feature SectionsMinEntropy (0.032226)
10. feature SizeOfOptionalHeader (0.031870)
11. feature SectionsMeanEntropy (0.025665)
12. feature MajorOperatingSystemVersion (0.022181)
13. feature ResourcesMaxEntropy (0.020268)

In [23]:
model = { "DecisionTree":tree.DecisionTreeClassifier(max_depth=10),
         "RandomForest":ek.RandomForestClassifier(n_estimators=50),
         "Adaboost":ek.AdaBoostClassifier(n_estimators=50),
         "GradientBoosting":ek.GradientBoostingClassifier(n_estimators=50),
         "GNB":GaussianNB(),
         "LinearRegression":LinearRegression()   
}

In [24]:
results = {}
for algo in model:
    clf = model[algo]
    clf.fit(X_train,y_train)
    score = clf.score(X_test,y_test)
    print ("%s : %s " %(algo, score))
    results[algo] = score

DecisionTree : 0.9897138717855849
RandomForest : 0.9942412169503803
Adaboost : 0.9847156827236508
GradientBoosting : 0.988120246287577
GNB : 0.7
LinearRegression : 0.5327803607306092

In [25]:
winner = max(results, key=results.get)

In [32]:
cur_model = model[winner].fit(X_train,y_train)
y_pred = cur_model.predict(X_test)

In [35]:
result=pandas.DataFrame({
    "Actual_Value":y_test,
    "Predict_Value":y_pred
})

In [36]:
result

       Actual_Value  Predict_Value
0                 0              0
1                 1              1
2                 1              1
3                 0              0
4                 0              0
5                 1              1
6                 1              1
7                 0              0
8                 0              0
9                 1              1
10                0              0
11                0              0
12                1              1
13                0              0
14                1              1
15                0              0
16                0              0
17                0              0
18                0              0
19                1              1
20                0              0
21                0              0
22                1              1
23                0              0
24                1              1
25                0              0
26                1              1
27                0              0
28                0              0
29                0              0
...             ...            ...
27580             1              1
27581             1              1
27582             1              1
27583             0              0
27584             0              0
27585             0              0
27586             0              0
27587             0              0
27588             0              0
27589             0              0
27590             0              0
27591             0              0
27592             1              1
27593             0              0
27594             0              0
27595             0              0
27596             0              0
27597             1              1
27598             0              0
27599             0              0
27600             0              0
27601             0              0
27602             0              0
27603             0              0
27604             0              0
27605             0              0
27606             0              0
27607             0              0
27608             0              0
27609             1              1

[27610 rows x 2 columns]